<?php
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
include $_SERVER['DOCUMENT_ROOT'] . '/AllRadio/TIForteFramework/Utils/LoadClass.class.php';
$__autoload = new LoadClass();
$__autoload->carregar('Ambiente;RadioAction');
$RadioAction = new RadioAction();
?>
<html>
    <head>
        <title> ♫ ♫ ♫ AllRadio ♫ ♫ ♫ </title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="shortcut icon" href="template/IMG/AllRadioFlaviconIco.ico" />
        <link rel="stylesheet" href="template/CSS/utils/utils.css" type="text/css" />
        <link rel="stylesheet" href="template/CSS/template/radio.css" type="text/css" />
        <script type="text/javascript" src="../../JScript/utils/jquery.js" ></script>
        <script type="text/javascript" src="../../JScript/utils/dw_misc.js" ></script>
        <script type="text/javascript" src="../../JScript/utils/dw_rolltip.js" ></script>
        <script type="text/javascript" src="../../JScript/utils/dw_viewport.js" ></script>
        <script type="text/javascript" src="../../JScript/utils/utils.js" ></script>
        <script type="text/javascript" src="../../JScript/template/radio.js" ></script>
    </head>
</html>
